### ISSUE TITLE
The extrinsic_T of ntu yaml

### ISSUE THREAD

**Issue by MatthewBlakeGE** [Kin-Zhang/FAST_LIO#2]
First of all, thank you for the data set you provided. When I used your data set for benchmarking recently, I found that many papers had biases in the ATE evaluation of the data set. Your true value should be in the Leica coordinate system. Maybe many people’s algorithm results are output In the body (IMU) coordinate system, they did not perform coordinate system conversion and directly evaluated them. Therefore, the errors are relatively large. In this evaluation of fast-lio, extrinsic_T should be [-0.05, 0.0, 0.055], because the extrinsic parameter in the paper is the conversion from lidar to imu. I used the wrong external parameters [0.05, 0.0, -0.055] to evaluate the eee_01 data set, and the result ATE was consistent with yours, which was 0.13. After using the correct external parameters [-0.05, 0.0, 0.055], the result was 0.082.Can you confirm this for me? Thank you.

**Comment by Kin-Zhang** [comment]
I think you should go for the paper author... Thien-Minh: @brytsknguyen

**Comment by MatthewBlakeGE** [comment]
Thank you for your reply,
